<script setup lang="ts">
import type { ApiSuccess } from '~/types/api'
import { apiErrorMessage } from '~/utils/api-error'
definePageMeta({ layout: 'dashboard', middleware: 'auth' }); useHead({ title: 'Santé système' })
type Health={status:string;checkedAt:string;application:{uptimeSeconds:number;node:string;rssBytes:string;heapUsedBytes:string;heapTotalBytes:string};host:{platform:string;release:string;cpuCount:number;loadAverage:number[];totalMemoryBytes:string;freeMemoryBytes:string};database:{reachable:boolean};security:{activeSessions:number;failedLoginsLastHour:number;auditFailuresLast24h:number};storage:{totalBytes:string;freeBytes:string;availableBytes:string}|null}
type Maintenance={maintenanceEnabled:boolean;maintenanceMessage:string|null;maintenanceStartsAt:string|null;maintenanceEndsAt:string|null}
const {data:healthData,error:healthError,refresh}=await useFetch<ApiSuccess<Health>>('/api/system/health')
const {data:maintenanceData,refresh:refreshMaintenance}=await useFetch<ApiSuccess<Maintenance>>('/api/system/maintenance')
const maintenance=reactive({enabled:false,message:'',startsAt:'',endsAt:''});watchEffect(()=>{const value=maintenanceData.value?.data;if(value){maintenance.enabled=value.maintenanceEnabled;maintenance.message=value.maintenanceMessage||'';maintenance.startsAt=value.maintenanceStartsAt?.slice(0,16)||'';maintenance.endsAt=value.maintenanceEndsAt?.slice(0,16)||''}})
const saveError=ref('');const saved=ref(false);async function save(){saveError.value='';saved.value=false;try{await $fetch('/api/system/maintenance',{method:'PUT',body:{enabled:maintenance.enabled,message:maintenance.message,startsAt:maintenance.startsAt||null,endsAt:maintenance.endsAt||null}});saved.value=true;await refreshMaintenance()}catch(error){saveError.value=apiErrorMessage(error,'Impossible de modifier la maintenance.')}}
const mb=(value:string)=>`${(Number(value)/1024/1024).toFixed(0)} Mo`;const gb=(value:string)=>`${(Number(value)/1024/1024/1024).toFixed(1)} Go`
</script>
<template><div><div class="page-head"><div><h1>Santé système</h1><p>État applicatif, base, ressources et sécurité récente.</p></div><button class="btn btn-secondary" type="button" @click="refresh()">Actualiser</button></div><div v-if="healthError" class="alert alert-error">Impossible de charger la santé système.</div><template v-else-if="healthData?.data"><div class="grid grid-4 metrics"><article class="card card-pad"><span>État</span><strong>{{healthData.data.status}}</strong><small>DB {{healthData.data.database.reachable?'joignable':'indisponible'}}</small></article><article class="card card-pad"><span>Sessions</span><strong>{{healthData.data.security.activeSessions}}</strong><small>{{healthData.data.security.failedLoginsLastHour}} échec(s) login / 1h</small></article><article class="card card-pad"><span>Mémoire app</span><strong>{{mb(healthData.data.application.rssBytes)}}</strong><small>Heap {{mb(healthData.data.application.heapUsedBytes)}}</small></article><article class="card card-pad"><span>Stockage</span><strong>{{healthData.data.storage?gb(healthData.data.storage.availableBytes):'N/A'}}</strong><small>disponible</small></article></div></template><section class="card card-pad maintenance"><h2>Mode maintenance</h2><p class="muted">Les pages publiques renvoient 503 pendant la fenêtre active. Les accès d’administration et les endpoints de sécurité restent disponibles.</p><div v-if="saved" class="alert alert-success">Configuration enregistrée.</div><div v-if="saveError" class="alert alert-error">{{saveError}}</div><div class="form-grid"><div class="field field-full"><label><input v-model="maintenance.enabled" type="checkbox"> Activer la maintenance</label></div><div class="field field-full"><label for="maint-message">Message</label><textarea id="maint-message" v-model="maintenance.message" class="textarea" /></div><div class="field"><label for="maint-start">Début</label><input id="maint-start" v-model="maintenance.startsAt" class="input" type="datetime-local"></div><div class="field"><label for="maint-end">Fin</label><input id="maint-end" v-model="maintenance.endsAt" class="input" type="datetime-local"></div></div><button class="btn btn-primary" type="button" @click="save">Enregistrer</button></section></div></template>
<style scoped>.metrics{margin-bottom:25px}.metrics article{display:flex;flex-direction:column}.metrics span,.metrics small{color:var(--ifics-muted)}.metrics strong{font-size:1.7rem;margin:4px 0}.maintenance{display:flex;flex-direction:column;gap:18px}.maintenance h2,.maintenance p{margin:0}</style>
