import { readBody } from 'h3'
import { requirePermission } from '../../utils/auth'
import { PERMISSIONS } from '../../utils/constants'
import { prisma } from '../../utils/prisma'
import { httpError, success } from '../../utils/api'
import { optionalDate, optionalString, requiredEnum, requiredString, safeObject, stringArray } from '../../utils/validation'
import { writeAuditLog } from '../../utils/audit'
const TYPES = ['EMPLOYEE', 'VOLUNTEER', 'INTERN', 'APPRENTICE', 'EXTERNAL'] as const
export default defineEventHandler(async (event) => { const context = await requirePermission(event, PERMISSIONS.HR_WRITE); const body = safeObject(await readBody(event)); const userId = requiredString(body.userId, 'Utilisateur', { max: 191 }); const user = await prisma.user.findFirst({ where: { id: userId, associationId: context.associationId }, select: { id: true } }); if (!user) httpError(404, 'Utilisateur introuvable.', 'USER_NOT_FOUND'); const profile = await prisma.hrProfile.upsert({ where: { userId }, create: { associationId: context.associationId, userId, employmentType: requiredEnum(body.employmentType, TYPES, 'Type'), startDate: optionalDate(body.startDate, 'Début'), endDate: optionalDate(body.endDate, 'Fin'), managerUserId: optionalString(body.managerUserId, 'Manager', { max: 191 }), skills: stringArray(body.skills ?? [], 'Compétences', { maxItems: 100, itemMax: 120 }), notes: optionalString(body.notes, 'Notes') }, update: { employmentType: requiredEnum(body.employmentType, TYPES, 'Type'), startDate: optionalDate(body.startDate, 'Début'), endDate: optionalDate(body.endDate, 'Fin'), managerUserId: optionalString(body.managerUserId, 'Manager', { max: 191 }), skills: stringArray(body.skills ?? [], 'Compétences', { maxItems: 100, itemMax: 120 }), notes: optionalString(body.notes, 'Notes') } }); await writeAuditLog(event, context, { action: 'HR_PROFILE_UPSERTED', entityType: 'HrProfile', entityId: profile.id, metadata: { userId } }); return success(profile) })
