<script setup lang="ts">
import type { ApiSuccess, SessionPayload } from '~/types/api'
import { apiErrorMessage } from '~/utils/api-error'

definePageMeta({layout:'dashboard',middleware:'auth'})
useHead({title:'Projet R&D'})
type Rnd={id:string;title:string;description:string|null;status:string;budget:string|null;repoUrl:string|null;documentationUrl:string|null;testResults:string|null;publicEnabled:boolean;ownerUserId:string|null;updatedAt:string}
const route=useRoute();const id=computed(()=>String(route.params.id))
const {data:session}=await useFetch<ApiSuccess<SessionPayload>>('/api/auth/me',{key:'session-me'})
const {data,error,refresh}=await useFetch<ApiSuccess<Rnd>>(()=>`/api/rnd/${id.value}`)
const item=computed(()=>data.value?.data??null);const permissions=computed(()=>session.value?.data.user.permissions??[]);const canWrite=computed(()=>permissions.value.includes('*')||permissions.value.includes('rnd:write'));const created=computed(()=>route.query.created==='1')
const form=reactive({title:'',description:'',status:'IDEA',budget:'',repoUrl:'',documentationUrl:'',testResults:'',publicEnabled:false});const saving=ref(false);const errorMessage=ref('');const successMessage=ref('')
watch(item,(value)=>{if(!value)return;form.title=value.title;form.description=value.description||'';form.status=value.status;form.budget=value.budget||'';form.repoUrl=value.repoUrl||'';form.documentationUrl=value.documentationUrl||'';form.testResults=value.testResults||'';form.publicEnabled=value.publicEnabled},{immediate:true})
async function save(){if(!canWrite.value||saving.value)return;saving.value=true;errorMessage.value='';successMessage.value='';try{await $fetch(`/api/rnd/${id.value}`,{method:'PUT',body:form});await refresh();successMessage.value='Projet R&D mis à jour.'}catch(error){errorMessage.value=apiErrorMessage(error,'Le projet R&D n’a pas pu être mis à jour.')}finally{saving.value=false}}
</script>
<template><div><div class="page-head"><div><h1>{{ item?.title||'Projet R&D' }}</h1><p>Suivi de l’expérimentation et de sa documentation.</p></div><div class="actions"><a v-if="item?.repoUrl" class="btn btn-secondary" :href="item.repoUrl" target="_blank" rel="noopener">Dépôt</a><a v-if="item?.documentationUrl" class="btn btn-secondary" :href="item.documentationUrl" target="_blank" rel="noopener">Documentation</a><NuxtLink class="btn btn-secondary" to="/dashboard/rnd">Retour</NuxtLink></div></div><div v-if="created" class="alert alert-success" style="margin-bottom:18px">Projet R&D créé.</div><div v-if="errorMessage" class="alert alert-error" style="margin-bottom:18px">{{ errorMessage }}</div><div v-if="successMessage" class="alert alert-success" style="margin-bottom:18px">{{ successMessage }}</div><div v-if="error" class="alert alert-error">Impossible de charger ce projet R&D.</div><form v-else-if="item&&canWrite" class="card card-pad" @submit.prevent="save"><div class="form-grid"><div class="field field-full"><label for="rnd-title">Titre *</label><input id="rnd-title" v-model="form.title" class="input" required maxlength="255"></div><div class="field"><label for="rnd-status">Statut</label><select id="rnd-status" v-model="form.status" class="select"><option value="IDEA">Idée</option><option value="EXPLORATION">Exploration</option><option value="PROTOTYPE">Prototype</option><option value="PILOT">Pilote</option><option value="ACTIVE">Actif</option><option value="ARCHIVED">Archivé</option></select></div><div class="field"><label for="rnd-budget">Budget (€)</label><input id="rnd-budget" v-model="form.budget" class="input" type="number" min="0" step="0.01"></div><div class="field field-full"><label for="rnd-description">Description</label><textarea id="rnd-description" v-model="form.description" class="textarea" rows="6" /></div><div class="field"><label for="rnd-repo">Dépôt</label><input id="rnd-repo" v-model="form.repoUrl" class="input" maxlength="500"></div><div class="field"><label for="rnd-docs">Documentation</label><input id="rnd-docs" v-model="form.documentationUrl" class="input" maxlength="500"></div><div class="field field-full"><label for="rnd-results">Résultats / observations</label><textarea id="rnd-results" v-model="form.testResults" class="textarea" rows="8" /></div></div><label style="display:flex;gap:8px;align-items:center;margin-top:14px"><input v-model="form.publicEnabled" type="checkbox"> Autoriser la visibilité publique</label><button class="btn btn-primary" type="submit" style="margin-top:18px" :disabled="saving">{{ saving?'Enregistrement…':'Enregistrer' }}</button></form><section v-else-if="item" class="card card-pad"><span class="badge">{{ item.status }}</span><h2>{{ item.title }}</h2><p>{{ item.description||'Aucune description.' }}</p><p v-if="item.testResults"><strong>Résultats :</strong> {{ item.testResults }}</p></section></div></template>
