<script setup lang="ts">
import type { ApiSuccess, SessionPayload } from '~/types/api'
import { apiErrorMessage } from '~/utils/api-error'

definePageMeta({ layout:'dashboard', middleware:'auth' })
useHead({ title:'Créer un projet R&D' })
const {data:session}=await useFetch<ApiSuccess<SessionPayload>>('/api/auth/me',{key:'session-me'})
const permissions=computed(()=>session.value?.data.user.permissions??[])
const canWrite=computed(()=>permissions.value.includes('*')||permissions.value.includes('rnd:write'))
const form=reactive({title:'',description:'',status:'IDEA',budget:'',repoUrl:'',documentationUrl:'',testResults:'',publicEnabled:false})
const saving=ref(false);const errorMessage=ref('')
async function submit(){if(!canWrite.value||saving.value)return;saving.value=true;errorMessage.value='';try{const response=await $fetch<ApiSuccess<{id:string}>>('/api/rnd/create',{method:'POST',body:form});await navigateTo(`/dashboard/rnd/${response.data.id}?created=1`)}catch(error){errorMessage.value=apiErrorMessage(error,'Le projet R&D n’a pas pu être créé.')}finally{saving.value=false}}
</script>
<template><div><div class="page-head"><div><h1>Nouveau projet R&D</h1><p>Documentez une idée, une expérimentation ou un prototype IFICS.</p></div><NuxtLink class="btn btn-secondary" to="/dashboard/rnd">Retour</NuxtLink></div><div v-if="!canWrite" class="alert alert-error">Votre rôle ne permet pas de créer un projet R&D.</div><form v-else class="card card-pad" @submit.prevent="submit"><div v-if="errorMessage" class="alert alert-error" style="margin-bottom:18px">{{ errorMessage }}</div><div class="form-grid"><div class="field field-full"><label for="rnd-title">Titre *</label><input id="rnd-title" v-model="form.title" class="input" required maxlength="255"></div><div class="field"><label for="rnd-status">Statut *</label><select id="rnd-status" v-model="form.status" class="select"><option value="IDEA">Idée</option><option value="EXPLORATION">Exploration</option><option value="PROTOTYPE">Prototype</option><option value="PILOT">Pilote</option><option value="ACTIVE">Actif</option><option value="ARCHIVED">Archivé</option></select></div><div class="field"><label for="rnd-budget">Budget (€)</label><input id="rnd-budget" v-model="form.budget" class="input" type="number" min="0" step="0.01"></div><div class="field field-full"><label for="rnd-description">Description</label><textarea id="rnd-description" v-model="form.description" class="textarea" rows="6" /></div><div class="field"><label for="rnd-repo">Dépôt</label><input id="rnd-repo" v-model="form.repoUrl" class="input" maxlength="500" placeholder="https://"></div><div class="field"><label for="rnd-docs">Documentation</label><input id="rnd-docs" v-model="form.documentationUrl" class="input" maxlength="500" placeholder="https://"></div><div class="field field-full"><label for="rnd-results">Résultats / observations</label><textarea id="rnd-results" v-model="form.testResults" class="textarea" rows="6" /></div></div><label style="display:flex;gap:8px;align-items:center;margin-top:14px"><input v-model="form.publicEnabled" type="checkbox"> Autoriser la visibilité publique</label><div class="actions" style="margin-top:22px"><button class="btn btn-primary" type="submit" :disabled="saving||!form.title.trim()">{{ saving?'Création…':'Créer le projet R&D' }}</button><NuxtLink class="btn btn-secondary" to="/dashboard/rnd">Annuler</NuxtLink></div></form></div></template>
