<script setup lang="ts">
import type { ApiSuccess, SessionPayload } from '~/types/api'
import { apiErrorMessage } from '~/utils/api-error'

definePageMeta({layout:'dashboard',middleware:'auth'})
useHead({title:'Profil RH'})
type UserOption={id:string;firstName:string;lastName:string;email:string;profileId:string|null}
type HrUser={id:string;firstName:string;lastName:string;email:string;status:string}
type Absence={id:string;type:string;startDate:string;endDate:string;status:string;note:string|null;createdAt:string}
type Training={id:string;title:string;provider:string|null;completedAt:string|null;expiresAt:string|null;createdAt:string}
type Review={id:string;reviewerUserId:string|null;reviewDate:string;summary:string;objectives:string|null;createdAt:string}
type Profile={id:string;userId:string;employmentType:string;startDate:string|null;endDate:string|null;managerUserId:string|null;skills:string[];notes:string|null;user:HrUser|null;manager:HrUser|null;absences:Absence[];trainings:Training[];reviews:Review[]}
const route=useRoute();const id=computed(()=>String(route.params.id))
const {data:session}=await useFetch<ApiSuccess<SessionPayload>>('/api/auth/me',{key:'session-me'})
const permissions=computed(()=>session.value?.data.user.permissions??[]);const canWrite=computed(()=>permissions.value.includes('*')||permissions.value.includes('hr:write'))
const {data,error,refresh}=await useFetch<ApiSuccess<Profile>>(()=>`/api/hr/${id.value}`);const profile=computed(()=>data.value?.data??null)
const {data:usersData}=await useFetch<ApiSuccess<UserOption[]>>('/api/hr/users',{immediate:canWrite.value});const users=computed(()=>usersData.value?.data??[])
const form=reactive({employmentType:'EMPLOYEE',startDate:'',endDate:'',managerUserId:'',skills:'',notes:''})
const absence=reactive({type:'Congé',startDate:'',endDate:'',status:'PENDING',note:''})
const training=reactive({title:'',provider:'',completedAt:'',expiresAt:''})
const review=reactive({reviewDate:'',summary:'',objectives:''})
const saving=ref(false);const addingAbsence=ref(false);const addingTraining=ref(false);const addingReview=ref(false);const errorMessage=ref('');const successMessage=ref('')
watch(profile,(value)=>{if(!value)return;form.employmentType=value.employmentType;form.startDate=value.startDate?value.startDate.slice(0,10):'';form.endDate=value.endDate?value.endDate.slice(0,10):'';form.managerUserId=value.managerUserId||'';form.skills=value.skills.join(', ');form.notes=value.notes||''},{immediate:true})
const fmt=(value:string|null)=>value?new Date(value).toLocaleDateString('fr-FR'):'—'
async function save(){if(!canWrite.value||saving.value||!profile.value)return;saving.value=true;errorMessage.value='';successMessage.value='';try{await $fetch('/api/hr/upsert',{method:'POST',body:{userId:profile.value.userId,employmentType:form.employmentType,startDate:form.startDate||undefined,endDate:form.endDate||undefined,managerUserId:form.managerUserId||undefined,skills:form.skills.split(',').map(item=>item.trim()).filter(Boolean),notes:form.notes}});await refresh();successMessage.value='Profil RH mis à jour.'}catch(error){errorMessage.value=apiErrorMessage(error,'Le profil RH n’a pas pu être mis à jour.')}finally{saving.value=false}}
async function addAbsence(){if(!canWrite.value||addingAbsence.value)return;addingAbsence.value=true;errorMessage.value='';successMessage.value='';try{await $fetch(`/api/hr/${id.value}/absence`,{method:'POST',body:absence});Object.assign(absence,{type:'Congé',startDate:'',endDate:'',status:'PENDING',note:''});await refresh();successMessage.value='Absence ajoutée.'}catch(error){errorMessage.value=apiErrorMessage(error,'L’absence n’a pas pu être ajoutée.')}finally{addingAbsence.value=false}}
async function addTraining(){if(!canWrite.value||addingTraining.value)return;addingTraining.value=true;errorMessage.value='';successMessage.value='';try{await $fetch(`/api/hr/${id.value}/training`,{method:'POST',body:{...training,completedAt:training.completedAt||undefined,expiresAt:training.expiresAt||undefined}});Object.assign(training,{title:'',provider:'',completedAt:'',expiresAt:''});await refresh();successMessage.value='Formation ajoutée.'}catch(error){errorMessage.value=apiErrorMessage(error,'La formation n’a pas pu être ajoutée.')}finally{addingTraining.value=false}}
async function addReview(){if(!canWrite.value||addingReview.value)return;addingReview.value=true;errorMessage.value='';successMessage.value='';try{await $fetch(`/api/hr/${id.value}/review`,{method:'POST',body:{...review,reviewDate:review.reviewDate||undefined}});Object.assign(review,{reviewDate:'',summary:'',objectives:''});await refresh();successMessage.value='Évaluation ajoutée.'}catch(error){errorMessage.value=apiErrorMessage(error,'L’évaluation n’a pas pu être ajoutée.')}finally{addingReview.value=false}}
</script>
<template><div><div class="page-head"><div><h1>{{ profile?.user ? `${profile.user.firstName} ${profile.user.lastName}` : 'Profil RH' }}</h1><p v-if="profile?.user">{{ profile.user.email }}</p></div><NuxtLink class="btn btn-secondary" to="/dashboard/hr">Retour aux profils</NuxtLink></div><div v-if="errorMessage" class="alert alert-error" style="margin-bottom:18px">{{ errorMessage }}</div><div v-if="successMessage" class="alert alert-success" style="margin-bottom:18px">{{ successMessage }}</div><div v-if="error" class="alert alert-error">Impossible de charger ce profil RH.</div><template v-else-if="profile"><form v-if="canWrite" class="card card-pad" style="margin-bottom:18px" @submit.prevent="save"><h2>Profil</h2><div class="form-grid"><div class="field"><label for="hr-type">Type</label><select id="hr-type" v-model="form.employmentType" class="select"><option value="EMPLOYEE">Salarié</option><option value="VOLUNTEER">Bénévole</option><option value="INTERN">Stagiaire</option><option value="APPRENTICE">Alternant</option><option value="EXTERNAL">Externe</option></select></div><div class="field"><label for="hr-manager">Manager</label><select id="hr-manager" v-model="form.managerUserId" class="select"><option value="">Aucun</option><option v-for="user in users" :key="user.id" :value="user.id">{{ user.firstName }} {{ user.lastName }}</option></select></div><div class="field"><label for="hr-start">Début</label><input id="hr-start" v-model="form.startDate" class="input" type="date"></div><div class="field"><label for="hr-end">Fin</label><input id="hr-end" v-model="form.endDate" class="input" type="date"></div><div class="field field-full"><label for="hr-skills">Compétences</label><input id="hr-skills" v-model="form.skills" class="input"></div><div class="field field-full"><label for="hr-notes">Notes</label><textarea id="hr-notes" v-model="form.notes" class="textarea" rows="4" /></div></div><button class="btn btn-primary" type="submit" style="margin-top:18px" :disabled="saving">{{ saving?'Enregistrement…':'Enregistrer' }}</button></form>
<div class="grid grid-2"><section class="card card-pad"><h2>Absences</h2><div v-if="!profile.absences.length" class="empty-state">Aucune absence.</div><div v-else class="table-wrap"><table><thead><tr><th>Type</th><th>Période</th><th>Statut</th></tr></thead><tbody><tr v-for="item in profile.absences" :key="item.id"><td>{{ item.type }}</td><td>{{ fmt(item.startDate) }} → {{ fmt(item.endDate) }}</td><td>{{ item.status }}</td></tr></tbody></table></div></section><form v-if="canWrite" class="card card-pad" @submit.prevent="addAbsence"><h2>Ajouter une absence</h2><div class="field"><label for="absence-type">Type *</label><input id="absence-type" v-model="absence.type" class="input" required maxlength="100"></div><div class="form-grid"><div class="field"><label for="absence-start">Début *</label><input id="absence-start" v-model="absence.startDate" class="input" type="date" required></div><div class="field"><label for="absence-end">Fin *</label><input id="absence-end" v-model="absence.endDate" class="input" type="date" required></div></div><div class="field"><label for="absence-status">Statut</label><select id="absence-status" v-model="absence.status" class="select"><option value="PENDING">En attente</option><option value="APPROVED">Approuvée</option><option value="REFUSED">Refusée</option></select></div><div class="field"><label for="absence-note">Note</label><textarea id="absence-note" v-model="absence.note" class="textarea" rows="3" /></div><button class="btn btn-primary" type="submit" :disabled="addingAbsence">Ajouter</button></form></div>
<div class="grid grid-2" style="margin-top:18px"><section class="card card-pad"><h2>Formations</h2><div v-if="!profile.trainings.length" class="empty-state">Aucune formation.</div><div v-else class="table-wrap"><table><thead><tr><th>Formation</th><th>Organisme</th><th>Réalisée</th><th>Expire</th></tr></thead><tbody><tr v-for="item in profile.trainings" :key="item.id"><td>{{ item.title }}</td><td>{{ item.provider||'—' }}</td><td>{{ fmt(item.completedAt) }}</td><td>{{ fmt(item.expiresAt) }}</td></tr></tbody></table></div></section><form v-if="canWrite" class="card card-pad" @submit.prevent="addTraining"><h2>Ajouter une formation</h2><div class="field"><label for="training-title">Formation *</label><input id="training-title" v-model="training.title" class="input" required maxlength="255"></div><div class="field"><label for="training-provider">Organisme</label><input id="training-provider" v-model="training.provider" class="input" maxlength="200"></div><div class="form-grid"><div class="field"><label for="training-completed">Réalisée le</label><input id="training-completed" v-model="training.completedAt" class="input" type="date"></div><div class="field"><label for="training-expires">Expire le</label><input id="training-expires" v-model="training.expiresAt" class="input" type="date"></div></div><button class="btn btn-primary" type="submit" :disabled="addingTraining||!training.title.trim()">Ajouter</button></form></div>
<section class="card card-pad" style="margin-top:18px"><h2>Évaluations</h2><div v-if="!profile.reviews.length" class="empty-state">Aucune évaluation.</div><div v-else style="display:grid;gap:10px"><article v-for="item in profile.reviews" :key="item.id" class="card card-pad"><strong>{{ fmt(item.reviewDate) }}</strong><p>{{ item.summary }}</p><p v-if="item.objectives" class="muted">Objectifs : {{ item.objectives }}</p></article></div></section><form v-if="canWrite" class="card card-pad" style="margin-top:18px" @submit.prevent="addReview"><h2>Ajouter une évaluation</h2><div class="field"><label for="review-date">Date</label><input id="review-date" v-model="review.reviewDate" class="input" type="date"></div><div class="field"><label for="review-summary">Synthèse *</label><textarea id="review-summary" v-model="review.summary" class="textarea" rows="5" required maxlength="20000" /></div><div class="field"><label for="review-objectives">Objectifs</label><textarea id="review-objectives" v-model="review.objectives" class="textarea" rows="4" maxlength="20000" /></div><button class="btn btn-primary" type="submit" :disabled="addingReview||!review.summary.trim()">Ajouter l’évaluation</button></form></template></div></template>
<style scoped>h2{margin-top:0}</style>
