<script setup lang="ts">
import type { ApiSuccess, SessionPayload } from '~/types/api'
import { apiErrorMessage } from '~/utils/api-error'

definePageMeta({layout:'dashboard',middleware:'auth'})
useHead({title:'Créer un profil RH'})
type UserOption={id:string;firstName:string;lastName:string;email:string;profileId:string|null}
const {data:session}=await useFetch<ApiSuccess<SessionPayload>>('/api/auth/me',{key:'session-me'})
const permissions=computed(()=>session.value?.data.user.permissions??[]);const canWrite=computed(()=>permissions.value.includes('*')||permissions.value.includes('hr:write'))
const {data:usersData}=await useFetch<ApiSuccess<UserOption[]>>('/api/hr/users',{immediate:canWrite.value});const users=computed(()=>usersData.value?.data??[]);const availableUsers=computed(()=>users.value.filter(user=>!user.profileId))
const form=reactive({userId:'',employmentType:'EMPLOYEE',startDate:'',endDate:'',managerUserId:'',skills:'',notes:''});const saving=ref(false);const errorMessage=ref('')
async function submit(){if(!canWrite.value||saving.value)return;saving.value=true;errorMessage.value='';try{await $fetch('/api/hr/upsert',{method:'POST',body:{userId:form.userId,employmentType:form.employmentType,startDate:form.startDate||undefined,endDate:form.endDate||undefined,managerUserId:form.managerUserId||undefined,skills:form.skills.split(',').map(item=>item.trim()).filter(Boolean),notes:form.notes}});await navigateTo('/dashboard/hr?created=1')}catch(error){errorMessage.value=apiErrorMessage(error,'Le profil RH n’a pas pu être créé.')}finally{saving.value=false}}
</script>
<template><div><div class="page-head"><div><h1>Nouveau profil RH</h1><p>Rattachez les informations RH à un compte utilisateur IFICS existant.</p></div><NuxtLink class="btn btn-secondary" to="/dashboard/hr">Retour</NuxtLink></div><div v-if="!canWrite" class="alert alert-error">Votre rôle ne permet pas d’administrer les données RH.</div><div v-else-if="!availableUsers.length" class="card card-pad"><h2>Aucun utilisateur sans profil RH</h2><p class="muted">Créez d’abord le compte utilisateur depuis l’administration ou modifiez un profil existant.</p><NuxtLink class="btn btn-secondary" to="/dashboard/hr">Retour aux profils</NuxtLink></div><form v-else class="card card-pad" @submit.prevent="submit"><div v-if="errorMessage" class="alert alert-error" style="margin-bottom:18px">{{ errorMessage }}</div><div class="form-grid"><div class="field field-full"><label for="hr-user">Utilisateur *</label><select id="hr-user" v-model="form.userId" class="select" required><option value="" disabled>Sélectionner un utilisateur</option><option v-for="user in availableUsers" :key="user.id" :value="user.id">{{ user.firstName }} {{ user.lastName }} — {{ user.email }}</option></select></div><div class="field"><label for="hr-type">Type *</label><select id="hr-type" v-model="form.employmentType" class="select"><option value="EMPLOYEE">Salarié</option><option value="VOLUNTEER">Bénévole</option><option value="INTERN">Stagiaire</option><option value="APPRENTICE">Alternant</option><option value="EXTERNAL">Externe</option></select></div><div class="field"><label for="hr-manager">Manager</label><select id="hr-manager" v-model="form.managerUserId" class="select"><option value="">Aucun</option><option v-for="user in users" :key="user.id" :value="user.id">{{ user.firstName }} {{ user.lastName }}</option></select></div><div class="field"><label for="hr-start">Début</label><input id="hr-start" v-model="form.startDate" class="input" type="date"></div><div class="field"><label for="hr-end">Fin</label><input id="hr-end" v-model="form.endDate" class="input" type="date"></div><div class="field field-full"><label for="hr-skills">Compétences</label><input id="hr-skills" v-model="form.skills" class="input" placeholder="Gestion de projet, réseau, formation…"><span class="help">Séparez les compétences par des virgules.</span></div><div class="field field-full"><label for="hr-notes">Notes internes</label><textarea id="hr-notes" v-model="form.notes" class="textarea" rows="5" /></div></div><div class="actions" style="margin-top:22px"><button class="btn btn-primary" type="submit" :disabled="saving||!form.userId">{{ saving?'Création…':'Créer le profil RH' }}</button><NuxtLink class="btn btn-secondary" to="/dashboard/hr">Annuler</NuxtLink></div></form></div></template>
