<script setup lang="ts">
import type { ApiSuccess } from '~/types/api'
definePageMeta({layout:'dashboard',middleware:'auth'});useHead({title:'Administration'})
type User={id:string;firstName:string;lastName:string;email:string;status:string;mfaEnabled:boolean;lastLoginAt:string|null;role:{code:string;name:string};_count:{sessions:number}}
type Audit={id:string;action:string;outcome:string;entityType:string|null;entityId:string|null;createdAt:string;user:{firstName:string;lastName:string;email:string}|null}
type AuditPage={items:Audit[];total:number;page:number;pages:number;limit:number}
const {data:usersData,error:usersError}=await useFetch<ApiSuccess<User[]>>('/api/users');const {data:auditData}=await useFetch<ApiSuccess<AuditPage>>('/api/audit',{query:{limit:20}});const users=computed(()=>usersData.value?.data??[]);const audit=computed(()=>auditData.value?.data.items??[]);const date=(v:string|null)=>v?new Date(v).toLocaleString('fr-FR'):'—'
</script>
<template><div><div class="page-head"><div><h1>Administration</h1><p>Comptes, MFA, sessions et journal d’audit.</p></div></div><section class="card card-pad admin-section"><h2>Utilisateurs</h2><div v-if="usersError" class="alert alert-error">Vous n’avez pas accès à la gestion des utilisateurs.</div><div v-else-if="users.length" class="table-wrap"><table><thead><tr><th>Utilisateur</th><th>Rôle</th><th>MFA</th><th>Sessions</th><th>Dernière connexion</th><th>Statut</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td><strong>{{ user.firstName }} {{ user.lastName }}</strong><br><small>{{ user.email }}</small></td><td>{{ user.role.name }}</td><td><span class="badge" :class="user.mfaEnabled?'':'badge-warning'">{{ user.mfaEnabled?'Actif':'Non activé' }}</span></td><td>{{ user._count.sessions }}</td><td>{{ date(user.lastLoginAt) }}</td><td>{{ user.status }}</td></tr></tbody></table></div></section><section class="card card-pad admin-section"><h2>Audit récent</h2><div v-if="!audit.length" class="empty-state">Aucune entrée d’audit accessible.</div><div v-else class="table-wrap"><table><thead><tr><th>Date</th><th>Action</th><th>Acteur</th><th>Ressource</th><th>Résultat</th></tr></thead><tbody><tr v-for="item in audit" :key="item.id"><td>{{ date(item.createdAt) }}</td><td><strong>{{ item.action }}</strong></td><td>{{ item.user ? `${item.user.firstName} ${item.user.lastName}` : 'Système/public' }}</td><td>{{ item.entityType || '—' }} {{ item.entityId || '' }}</td><td><span class="badge" :class="item.outcome==='FAILURE'?'badge-danger':''">{{ item.outcome }}</span></td></tr></tbody></table></div></section></div></template>
<style scoped>.admin-section{margin-bottom:22px}.admin-section h2{margin-top:0}</style>
