<script setup lang="ts">
import type { ApiSuccess, SessionPayload } from '~/types/api'
import { apiErrorMessage } from '~/utils/api-error'

definePageMeta({ layout:'dashboard', middleware:'auth' })
useHead({ title:'Contenu CMS' })

type Entry={id:string;kind:string;slug:string;titleFr:string;titleEn:string|null;excerptFr:string|null;excerptEn:string|null;bodyFr:string;bodyEn:string|null;heroImageUrl:string|null;featured:boolean;status:string;scheduledAt:string|null;publishedAt:string|null;archivedAt:string|null;updatedAt:string}
const route=useRoute();const id=computed(()=>String(route.params.id))
const {data:session}=await useFetch<ApiSuccess<SessionPayload>>('/api/auth/me',{key:'session-me'})
const {data,error,refresh}=await useFetch<ApiSuccess<Entry>>(()=>`/api/content/${id.value}`)
const entry=computed(()=>data.value?.data??null)
const permissions=computed(()=>session.value?.data.user.permissions??[])
const canWrite=computed(()=>permissions.value.includes('*')||permissions.value.includes('content:write'))
const canPublish=computed(()=>permissions.value.includes('*')||permissions.value.includes('content:publish'))
const created=computed(()=>route.query.created==='1')
const form=reactive({titleFr:'',titleEn:'',excerptFr:'',excerptEn:'',bodyFr:'',bodyEn:'',heroImageUrl:'',featured:false})
const scheduledAt=ref('');const saving=ref(false);const changing=ref(false);const errorMessage=ref('');const successMessage=ref('')
watch(entry,(value)=>{if(!value)return;form.titleFr=value.titleFr;form.titleEn=value.titleEn||'';form.excerptFr=value.excerptFr||'';form.excerptEn=value.excerptEn||'';form.bodyFr=value.bodyFr;form.bodyEn=value.bodyEn||'';form.heroImageUrl=value.heroImageUrl||'';form.featured=value.featured;scheduledAt.value=value.scheduledAt?value.scheduledAt.slice(0,16):''},{immediate:true})
const nextStatuses=computed(()=>{if(!entry.value)return[] as string[];const map:Record<string,string[]>={DRAFT:['REVIEW'],REVIEW:['DRAFT','APPROVED'],APPROVED:['DRAFT','SCHEDULED','PUBLISHED'],SCHEDULED:['PUBLISHED','ARCHIVED'],PUBLISHED:['ARCHIVED'],ARCHIVED:['DRAFT']};return(map[entry.value.status]||[]).filter(status=>!['APPROVED','SCHEDULED','PUBLISHED','ARCHIVED'].includes(status)||canPublish.value)})
function statusLabel(value:string){return({DRAFT:'Brouillon',REVIEW:'En revue',APPROVED:'Approuvé',SCHEDULED:'Programmé',PUBLISHED:'Publié',ARCHIVED:'Archivé'} as Record<string,string>)[value]||value}
async function save(){if(!canWrite.value||saving.value||entry.value?.status==='PUBLISHED')return;saving.value=true;errorMessage.value='';successMessage.value='';try{await $fetch(`/api/content/${id.value}`,{method:'PUT',body:form});await refresh();successMessage.value='Contenu mis à jour.'}catch(error){errorMessage.value=apiErrorMessage(error,'Le contenu n’a pas pu être enregistré.')}finally{saving.value=false}}
async function changeStatus(status:string){if(!canWrite.value||changing.value)return;changing.value=true;errorMessage.value='';successMessage.value='';try{await $fetch(`/api/content/${id.value}/status`,{method:'POST',body:{status,scheduledAt:status==='SCHEDULED'?scheduledAt.value:undefined}});await refresh();successMessage.value=`Statut : ${statusLabel(status)}.`}catch(error){errorMessage.value=apiErrorMessage(error,'Le changement de statut a échoué.')}finally{changing.value=false}}
</script>

<template><div><div class="page-head"><div><h1>{{ entry?.titleFr||'Contenu' }}</h1><p v-if="entry">/{{ entry.slug }} · {{ entry.kind }}</p></div><NuxtLink class="btn btn-secondary" to="/dashboard/content">Retour aux contenus</NuxtLink></div>
<div v-if="created" class="alert alert-success" style="margin-bottom:18px">Brouillon créé.</div><div v-if="errorMessage" class="alert alert-error" style="margin-bottom:18px">{{ errorMessage }}</div><div v-if="successMessage" class="alert alert-success" style="margin-bottom:18px">{{ successMessage }}</div><div v-if="error" class="alert alert-error">Impossible de charger ce contenu.</div>
<template v-else-if="entry"><section class="card card-pad" style="margin-bottom:18px"><div class="actions"><span class="badge">{{ statusLabel(entry.status) }}</span><span v-if="entry.featured" class="badge badge-muted">À la une</span></div><p><strong>Dernière modification :</strong> {{ new Date(entry.updatedAt).toLocaleString('fr-FR') }}</p><p v-if="entry.publishedAt"><strong>Publication :</strong> {{ new Date(entry.publishedAt).toLocaleString('fr-FR') }}</p></section>
<form v-if="canWrite && entry.status!=='PUBLISHED'" class="card card-pad" style="margin-bottom:18px" @submit.prevent="save"><h2>Édition</h2><div class="form-grid"><div class="field"><label for="cms-title-fr">Titre FR *</label><input id="cms-title-fr" v-model="form.titleFr" class="input" required maxlength="255"></div><div class="field"><label for="cms-title-en">Titre EN</label><input id="cms-title-en" v-model="form.titleEn" class="input" maxlength="255"></div><div class="field field-full"><label for="cms-excerpt-fr">Résumé FR</label><textarea id="cms-excerpt-fr" v-model="form.excerptFr" class="textarea" rows="3" /></div><div class="field field-full"><label for="cms-body-fr">Contenu FR *</label><textarea id="cms-body-fr" v-model="form.bodyFr" class="textarea" rows="14" required maxlength="200000" /></div><div class="field field-full"><label for="cms-excerpt-en">Résumé EN</label><textarea id="cms-excerpt-en" v-model="form.excerptEn" class="textarea" rows="3" /></div><div class="field field-full"><label for="cms-body-en">Contenu EN</label><textarea id="cms-body-en" v-model="form.bodyEn" class="textarea" rows="10" maxlength="200000" /></div><div class="field field-full"><label for="cms-image">URL image</label><input id="cms-image" v-model="form.heroImageUrl" class="input" maxlength="500"></div></div><label style="display:flex;gap:8px;align-items:center;margin-top:14px"><input v-model="form.featured" type="checkbox"> À la une</label><button class="btn btn-primary" type="submit" style="margin-top:18px" :disabled="saving">{{ saving?'Enregistrement…':'Enregistrer' }}</button></form>
<section v-if="canWrite" class="card card-pad"><h2>Workflow éditorial</h2><div v-if="entry.status==='APPROVED'&&canPublish" class="field" style="max-width:420px;margin-bottom:16px"><label for="cms-schedule">Date pour une publication programmée</label><input id="cms-schedule" v-model="scheduledAt" class="input" type="datetime-local"></div><div class="actions"><button v-for="status in nextStatuses" :key="status" class="btn" :class="['ARCHIVED','DRAFT'].includes(status)?'btn-secondary':'btn-primary'" type="button" :disabled="changing||(status==='SCHEDULED'&&!scheduledAt)" @click="changeStatus(status)">{{ statusLabel(status) }}</button></div><p v-if="!nextStatuses.length" class="muted">Aucune transition disponible avec vos permissions.</p></section></template></div></template>

<style scoped>h2{margin-top:0}</style>
