import { readBody } from 'h3'
import { requirePermission } from '../../utils/auth'
import { PERMISSIONS } from '../../utils/constants'
import { prisma } from '../../utils/prisma'
import { httpError, success } from '../../utils/api'
import { optionalDate, optionalEnum, optionalString, requiredString, safeObject } from '../../utils/validation'
import { writeAuditLog } from '../../utils/audit'
const STATUSES = ['TODO', 'IN_PROGRESS', 'BLOCKED', 'DONE'] as const; const PRIORITIES = ['LOW', 'NORMAL', 'HIGH', 'URGENT'] as const
export default defineEventHandler(async (event) => { const context = await requirePermission(event, PERMISSIONS.PROJECT_WRITE); const body = safeObject(await readBody(event)); const projectId = optionalString(body.projectId, 'Projet', { max: 191 }); if (projectId) { const project = await prisma.project.findFirst({ where: { id: projectId, associationId: context.associationId, archivedAt: null }, select: { id: true } }); if (!project) httpError(404, 'Projet introuvable.', 'PROJECT_NOT_FOUND') } const assigneeUserId = optionalString(body.assigneeUserId, 'Assigné', { max: 191 }); if (assigneeUserId) { const user = await prisma.user.findFirst({ where: { id: assigneeUserId, associationId: context.associationId, status: 'ACTIVE' }, select: { id: true } }); if (!user) httpError(400, 'Utilisateur assigné invalide.', 'INVALID_ASSIGNEE') } const task = await prisma.workTask.create({ data: { associationId: context.associationId, projectId, title: requiredString(body.title, 'Titre', { max: 255 }), description: optionalString(body.description, 'Description'), status: optionalEnum(body.status, STATUSES, 'Statut') || 'TODO', priority: optionalEnum(body.priority, PRIORITIES, 'Priorité') || 'NORMAL', assigneeUserId, dueDate: optionalDate(body.dueDate, 'Échéance'), createdByUserId: context.userId } }); await writeAuditLog(event, context, { action: 'TASK_CREATED', entityType: 'WorkTask', entityId: task.id, metadata: { projectId, assigneeUserId } }); return success(task) })
