<script setup lang="ts">
import type { ApiSuccess, SessionPayload } from '~/types/api'
import { apiErrorMessage } from '~/utils/api-error'

definePageMeta({layout:'dashboard',middleware:'auth'})
useHead({title:'Ajouter un matériel'})
type UserOption={id:string;firstName:string;lastName:string;email:string}
const {data:session}=await useFetch<ApiSuccess<SessionPayload>>('/api/auth/me',{key:'session-me'})
const permissions=computed(()=>session.value?.data.user.permissions??[]);const canWrite=computed(()=>permissions.value.includes('*')||permissions.value.includes('it:write'))
const {data:usersData}=await useFetch<ApiSuccess<UserOption[]>>('/api/assets/users',{immediate:canWrite.value});const users=computed(()=>usersData.value?.data??[])
const form=reactive({inventoryTag:'',type:'LAPTOP',brand:'',model:'',serialNumber:'',status:'STOCK',assignedUserId:'',location:'',purchaseDate:'',warrantyUntil:'',notes:''})
const saving=ref(false);const errorMessage=ref('')
watch(()=>form.assignedUserId,(value)=>{if(value&&form.status==='STOCK')form.status='ASSIGNED'})
async function submit(){if(!canWrite.value||saving.value)return;saving.value=true;errorMessage.value='';try{await $fetch('/api/assets/create',{method:'POST',body:{...form,assignedUserId:form.assignedUserId||undefined,purchaseDate:form.purchaseDate||undefined,warrantyUntil:form.warrantyUntil||undefined}});await navigateTo('/dashboard/assets?created=1')}catch(error){errorMessage.value=apiErrorMessage(error,'Le matériel n’a pas pu être créé.')}finally{saving.value=false}}
</script>
<template><div><div class="page-head"><div><h1>Nouveau matériel</h1><p>Ajoutez un équipement au parc IT IFICS.</p></div><NuxtLink class="btn btn-secondary" to="/dashboard/assets">Retour</NuxtLink></div><div v-if="!canWrite" class="alert alert-error">Votre rôle ne permet pas d’administrer le parc IT.</div><form v-else class="card card-pad" @submit.prevent="submit"><div v-if="errorMessage" class="alert alert-error" style="margin-bottom:18px">{{ errorMessage }}</div><div class="form-grid"><div class="field"><label for="asset-tag">Référence inventaire *</label><input id="asset-tag" v-model="form.inventoryTag" class="input" maxlength="100" required></div><div class="field"><label for="asset-type">Type *</label><input id="asset-type" v-model="form.type" class="input" maxlength="100" required placeholder="LAPTOP, PHONE, MONITOR…"></div><div class="field"><label for="asset-brand">Marque</label><input id="asset-brand" v-model="form.brand" class="input" maxlength="100"></div><div class="field"><label for="asset-model">Modèle</label><input id="asset-model" v-model="form.model" class="input" maxlength="150"></div><div class="field"><label for="asset-serial">Numéro de série</label><input id="asset-serial" v-model="form.serialNumber" class="input" maxlength="150"></div><div class="field"><label for="asset-status">Statut</label><select id="asset-status" v-model="form.status" class="select"><option value="STOCK">En stock</option><option value="ASSIGNED">Affecté</option><option value="MAINTENANCE">Maintenance</option><option value="RETIRED">Retiré</option><option value="LOST">Perdu</option></select></div><div class="field"><label for="asset-user">Affecté à</label><select id="asset-user" v-model="form.assignedUserId" class="select"><option value="">Personne</option><option v-for="user in users" :key="user.id" :value="user.id">{{ user.firstName }} {{ user.lastName }} — {{ user.email }}</option></select></div><div class="field"><label for="asset-location">Localisation</label><input id="asset-location" v-model="form.location" class="input" maxlength="200"></div><div class="field"><label for="asset-purchase">Date d’achat</label><input id="asset-purchase" v-model="form.purchaseDate" class="input" type="date"></div><div class="field"><label for="asset-warranty">Garantie jusqu’au</label><input id="asset-warranty" v-model="form.warrantyUntil" class="input" type="date"></div><div class="field field-full"><label for="asset-notes">Notes</label><textarea id="asset-notes" v-model="form.notes" class="textarea" rows="5" /></div></div><div class="actions" style="margin-top:22px"><button class="btn btn-primary" type="submit" :disabled="saving||!form.inventoryTag.trim()||!form.type.trim()">{{ saving?'Création…':'Ajouter au parc' }}</button><NuxtLink class="btn btn-secondary" to="/dashboard/assets">Annuler</NuxtLink></div></form></div></template>
